### ISSUE TITLE
Missing input files

### ISSUE THREAD

**Issue by ghost** [RayRuizhiLiao/joint_chestxray#2]
I'm trying to get your code to run but some necessary input files seem to be missing, in particular from `scripts/main./py`
```python
    if args.do_train:
        [ ...]
        '''
        Load a pretrained joint model or pretrained BERT model 
        '''
        config = BertConfig.from_json_file(os.path.join(args.bert_pretrained_dir, 
                                                        args.config_name))
```
with runtime error:
```
  File "/home/gabyvs/anaconda3/envs/Chauhan_et_al_2020/lib/python3.7/site-packages/pytorch_transformers/modeling_utils.py", line 233, in from_json_file
    with open(json_file, "r", encoding='utf-8') as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/data/vision/polina/projects/chestxray/geeticka/bert/scibert/scibert_scivocab_uncased/bert_config.json'
```
which perhaps isn't surprising that it fails as the path `/data/vision/polina/...` (found in `parser.py`) doesn't exist on my system. However, even if I fixed the file path, I still cannot find the file `bert_config.js` anywhere from this repository. Similar for other input files / paths.

Additionally, if this is the first time around for training, there will be no pre-trained model to load and this will fail (as will subsequent lines). Chicken-and-egg, or am I missing something?

I can give you a somewhat refactored `parser.py` which groups a lot of the common path prefixes (e.g. "/data/vision/polina" etc), if that helps?

**Comment by rayruizhiliao** [comment]
Please find the pre-trained BERT in this section: https://github.com/RayRuizhiLiao/joint_chestxray#bert

Thanks for pointing this out!

**Comment by Naylenv** [comment]
I download the pre-trained BERT from dropbox。I have a quession，there are two compressed packs in the folder. (1)I am directly extracting the file, or (2)I need to decompress the compression package in the folder？

**Comment by ghost** [comment]
IIRC, just uncompress the `scibert.tar.gz` (e.g. `tar xzf scibert.tar.gz`) 

There is a `scibert.tar.gz` and a `weights.tar.gz`
If you look inside them:
  - scibert.tar.gz:
    - bert_config.json
    - pytorch_model.bin
    - vocab.txt
  - weights.tar.gz:
    - bert_config.json
    - pytorch_model.bin

Whereby the files `bert_config.json` and `pytorch_model.bin` are identical in both `*.tar.gz` files.

At least, when I just decompress / expand the `scibert.tar.gz` both the supervised and unsupervised training run to completion, which I always see as a good sign :)
HTH

BTW: "Turn inward and examine yourself when you encounter difficulties in life." - nice :-) and actually rather appropriate for me right now...

**Comment by njan-creative** [comment]
MIMIC-CXR has a standard train, valid, test split.
Does this use the samples from valid and test split ?
