### ISSUE TITLE
How could I use the pre-trained BERT

### ISSUE THREAD

**Issue by Naylenv** [RayRuizhiLiao/joint_chestxray#3]
I download the pre-trained BERT from dropbox。I have a quession，there are two compressed packs in the folder. (1)I am directly extracting the file, or (2)I need to decompress the compression package in the folder？

**Comment by rayruizhiliao** [comment]
Hope this comment is helpful! https://github.com/RayRuizhiLiao/joint_chestxray/issues/2#issuecomment-1018545006
